name: sharik
description: Sharik is an app for sending files to almost any device. No internet connection needed.
homepage: https://github.com/marchellodev/sharik
repository: https://github.com/marchellodev/sharik
issue_tracker: https://github.com/marchellodev/sharik/issues
publish_to: none
version: 2.2.0
versionCode: 4
author: marchellodev

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.17.4
  google_fonts: ^1.0.0
  intro_slider: ^2.2.9

  # for android (https://github.com/miguelpruivo/flutter_file_picker/issues/223)
  file_picker: 1.4.3+2

  # for desktop
#  file_picker: ^1.7.0

  url_launcher: ^5.4.5
  wifi_iot: ^0.1.1
  clipboard_manager: ^0.0.4
  path_provider: ^1.6.7
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  device_apps: ^1.0.9
  provider: ^4.0.5
  http: ^0.12.0+4
  package_info: ^0.4.0+17

  ping_discover_network: ^0.2.0+1




dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.9.0

  pedantic: ^1.9.0

flutter:

  assets:
    - assets/
    - google_fonts/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
