name: sharik
description: Sharik is an open-source, cross-platform solution for sharing files via Wi-Fi or Mobile Hotspot
homepage: https://github.com/marchellodev/sharik
repository: https://github.com/marchellodev/sharik
issue_tracker: https://github.com/marchellodev/sharik/issues
publish_to: none
version: 2.5.0
versionCode: 6
author: marchellodev

environment:
  sdk: ">=2.6.0 <3.0.0"

# todo verify & sync google_fonts files
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # UI
  flutter_svg: ^0.19.2+1
  google_fonts: ^1.1.2
  intro_slider: ^2.3.3
  responsive_framework: ^0.0.14


  # UTILS
  http: ^0.12.0+2
  wifi_iot: ^0.2.0
  ping_discover_network: ^0.2.0+1
  simple_connectivity: ^0.1.1

  path_provider: ^1.6.27
  url_launcher: ^5.7.10
  device_apps: ^1.2.0

  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  package_info: ^0.4.3+4

  usage: ^4.0.0

  intl: ^0.17.0-nullsafety.2


  file_selector: ^0.7.0+2
  file_selector_windows: ^0.0.2


  # ARCHITECTURE
  provider: ^4.3.3


  # DESKTOP-SPECIFIC
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 85dde09b702a0cb1f5e1392d2f030bdc3d4e5be3




dev_dependencies:
  build_runner: any
  hive_generator: ^0.8.2

  #  intl_translation: ^0.17.10+1
  lint: ^1.5.1

flutter:
  generate: true
  uses-material-design: false

  assets:
    - assets/slides/
    - assets/flags/
    - assets/
    - google_fonts/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
