name: sharik
description: Sharik is an app for sending files to almost any device. No internet connection needed.
homepage: https://github.com/marchellodev/sharik
repository: https://github.com/marchellodev/sharik
issue_tracker: https://github.com/marchellodev/sharik/issues
publish_to: none
version: 2.2.0
versionCode: 4
author: marchellodev

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.18.0
  google_fonts: ^1.1.0
  intro_slider: ^2.3.1

  # for android (https://github.com/miguelpruivo/flutter_file_picker/issues/223)
#  file_picker: 1.4.3+2

  # for desktop
  file_picker: ^1.12.0

  url_launcher: ^5.4.11
  wifi_iot: ^0.1.1
  path_provider: ^1.6.11
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  device_apps: ^1.0.10
  provider: ^4.1.3
  http: ^0.12.1
  package_info: ^0.4.1

  ping_discover_network: ^0.2.0+1




dev_dependencies:
  hive_generator: any
  build_runner: ^1.10.0

  pedantic: ^1.9.0

flutter:

  assets:
    - assets/
    - google_fonts/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf

  uses-material-design: false