name: sharik
description: Sharik is an open-source, cross-platform solution for sharing files via Wi-Fi or Mobile Hotspot
homepage: https://github.com/marchellodev/sharik
repository: https://github.com/marchellodev/sharik
issue_tracker: https://github.com/marchellodev/sharik/issues
publish_to: none
version: 3.0.0
versionCode: 8
author: marchellodev

environment:
  sdk: '>=2.12.0 <3.0.0'

# todo verify & sync google_fonts files
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # UI
  flutter_feather_icons: ^2.0.0+1
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  intro_slider: ^2.4.3
  responsive_framework: ^0.1.0

  qr_flutter: ^4.0.0
  flutter_markdown: ^0.6.2

  wakelock: ^0.5.2

  #  device_preview: ^0.7.1


  # todo https://pub.dev/packages/flutter_native_splash

  # UTILS
  http: ^0.13.3

  path_provider: ^2.0.2
  url_launcher: ^6.0.3
  device_apps: ^2.1.1

  hive: ^2.0.4
  hive_flutter: ^1.0.0


  intl: ^0.17.0
  collection: ^1.15.0


  # Android and IOS
  file_picker: ^3.0.2+2


  # Desktop
  file_selector: ^0.8.2
  file_selector_windows: ^0.0.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4



  # ARCHITECTURE
  provider: ^5.0.0




dev_dependencies:
  build_runner: ^2.0.4
  hive_generator: ^1.1.0

  lint: ^1.5.3

  flutter_native_splash: ^1.1.8+4


flutter_native_splash:
  # [Colors.deepPurple.shade400]
  color: "#7E57C2"
  web: false

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/slides/
    - assets/flags/
    - assets/icons/social/
    - assets/
    - google_fonts/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
        - asset: fonts/JetBrainsMono-Medium.ttf
          weight: 500
        #        - asset: fonts/JetBrainsMono-SemiBold.ttf
        #          weight: 600
        - asset: fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: fonts/JetBrainsMono-ExtraBold.ttf
          weight: 800
