name: sharik
description: Sharik is an open-source, cross-platform solution for sharing files via Wi-Fi or Mobile Hotspot
homepage: https://github.com/marchellodev/sharik
repository: https://github.com/marchellodev/sharik
issue_tracker: https://github.com/marchellodev/sharik/issues
publish_to: none
version: 2.5.0
versionCode: 6
author: marchellodev

environment:
  sdk: '>=2.12.0 <3.0.0'

# todo verify & sync google_fonts files
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # UI
  flutter_svg: ^0.21.0-nullsafety.0
  google_fonts: ^2.0.0
  intro_slider: ^2.3.4
  responsive_framework: ^0.0.15


  # UTILS
  http: ^0.13.0
  wifi_iot: ^0.2.2
  ping_discover_network: ^0.2.0+1
  simple_connectivity: ^0.1.1

  path_provider: ^2.0.1
  url_launcher: ^6.0.2
  device_apps: ^1.3.0

  hive: ^2.0.0
  hive_flutter: ^1.0.0

  package_info: ^2.0.0

  usage: ^4.0.0

  intl: ^0.17.0
  collection: ^1.15.0


  file_selector: ^0.8.2
  file_selector_windows: ^0.0.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4

  # Android and IOS
  file_picker: ^3.0.0


  # ARCHITECTURE
  provider: ^5.0.0


  # DESKTOP-SPECIFIC
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 85dde09b702a0cb1f5e1392d2f030bdc3d4e5be3






dev_dependencies:
  build_runner: ^1.11.5
  hive_generator: ^1.0.0

  #  intl_translation: ^0.17.10+1
  lint: ^1.5.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/slides/
    - assets/flags/
    - assets/icons/social/
    - assets/
    - google_fonts/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
