name: sharik
description: Sharik is an open-source, cross-platform solution for sharing files via Wi-Fi or Mobile Hotspot
homepage: https://github.com/marchellodev/sharik
repository: https://github.com/marchellodev/sharik
issue_tracker: https://github.com/marchellodev/sharik/issues
publish_to: none
version: 2.5.0
versionCode: 6
author: marchellodev

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_svg: ^0.19.0
  google_fonts: ^1.1.0
  intro_slider: ^2.3.1
  responsive_framework: ^0.0.8

  # UTILS
  http: ^0.12.2
  wifi_iot: ^0.1.1
  ping_discover_network: ^0.2.0+1
  simple_connectivity: ^0.1.1

  path_provider: ^1.6.14
  url_launcher: ^5.5.0

  file_picker: ^1.13.3
  device_apps: ^1.2.0

  hive: ^1.4.4
  hive_flutter: ^0.3.1

  package_info: ^0.4.3

  usage: ^3.4.2

  # ARCHITECTURE
  provider: ^4.3.2+1

  sharik_wrapper:
    # path: /Users/admin/sharik_wrapper
    git: https://github.com/marchellodev/sharik_wrapper

dev_dependencies:
  hive_generator: any
  build_runner: any

  lint: any

flutter:
  uses-material-design: false

  assets:
    - assets/
    - google_fonts/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
