name: Sharik
description: Sharik is an app for sending files to almost any device. No internet connection needed.
homepage: https://github.com/marchellodev/sharik
repository: https://github.com/marchellodev/sharik
issue_tracker: https://github.com/marchellodev/sharik/issues
publish_to: none
version: 1.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.17.2
  google_fonts: ^0.3.9
  intro_slider: ^2.2.9
  file_picker: ^1.4.3+2
  shared_preferences: ^0.5.6+2
  url_launcher: ^5.4.2
  wifi_iot: ^0.1.1
  clipboard_manager: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/
    - google_fonts/